Eudhyog/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('home.urls')),
    url(r'',include('product.urls')),
    url(r'^forum/',include('forum.urls')),
    url(r'^filter/',include('filter.urls',namespace='filter')),
    url(r'^account/',include('authentication.urls')),




]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

filter/urls.py
from django.conf.urls import url
from .views import profilter

urlpatterns = [
    url(r'^market/', profilter, name='product-filter'),
]

home/urls.py
from django.conf.urls import url
from .views import (ProductListView,volunteer,home,contact,projects,Knitting,
SupplierFormView, ContactSupplier,training,trainingdetail)



urlpatterns = [
	url(r'^$',home, name='home'),
    url(r'^market/$',ProductListView.as_view(), name='market'),
    
    url(r'^volunteer/$',volunteer, name='volunteer'),
    url(r'^training/$',training, name='training'),
    url(r'^project/$',projects, name='project'),
    url(r'^contact/$',contact, name='contact'),
    url(r'^train/$',trainingdetail, name='train'),
    url(r'^knitting/$',Knitting.as_view(), name='knitting'),
	url(r'^supplier-form/$', SupplierFormView.as_view(), name='supplier-form'),
    url(r'^contact-supplier/$', ContactSupplier.as_view(), name='contact-supplier'),

]

home/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Supplier(models.Model):
	BUSINESS_CHOICES = (
        ('KS', 'Knitting & Stiching'),
        ('HNDCRFTS', 'Handicrafts'),
        ('OD', 'Ornament Designs'),
        ('DCRNTS', 'Decorations'),
        ('WC', 'Wood Carving'),
        ('AH', 'Animal Husbandary'),
        ('SS', 'Statue Sculpture'),
        ('MD', 'Mask & Dolls'),

    )
	name = models.CharField(max_length=50)
	organization = models.CharField(max_length=50, blank = True)
	location = models.CharField(max_length=30)
	contact = models.CharField(max_length=50)
	business_type = models.CharField(max_length=100, choices = BUSINESS_CHOICES)
	product_name = models.CharField(max_length=50)
	product_price = models.CharField(max_length=50)
	product_image = models.ImageField(upload_to = 'Product Photos')
	publish = models.BooleanField(default=False)

	def __str__(self):
		return 'Supplier Name: {}, Product name : {}'.format(self.name,self.product_name)

home/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, FormView
from product.models import Product
from .models import Supplier
from django.views.generic.list import ListView

from .supplyforms import SupplierForm


# Create your views here.
def home(request):
	template_name='index.html'
	return render(request,template_name)

class ProductListView(ListView):
	model=Product
	template_name='market.html'

	def get_context_data(self,**kwargs):
		context=super(ProductListView,self).get_context_data(*kwargs)
		context['product']=Product.objects.all()
		return context



def volunteer(request):
	template_name='volunteer1.html'
	return render(request,template_name)

def projects(request):
	template_name='project.html'
	return render(request,template_name)


def training(request):
	template_name='training.html'
	return render(request,template_name)

def contact(request):
	template_name='contact.html'
	return render(request,template_name)

class Knitting(TemplateView):
	template_name = 'project-knitting1.html'

	def get_context_data(self, **kwargs):
		context = super(Knitting, self).get_context_data(**kwargs)
		context['supplier'] = Supplier.objects.all()[:3]
		return context


class SupplierFormView(FormView):
	form_class = SupplierForm
	# model = Contact
	initial = {'key': 'value'}
	template_name = 'supplier_form.html'
	success_url = '/thanks/'

	def get(self, request, *args, **kwargs):
		form = self.form_class(initial=self.initial)
		return render(request, self.template_name, {'form': form})


	def post(self, request, *args, **kwargs):
		form = self.form_class(request.POST, request.FILES)
		if form.is_valid():
			form.save()
			return redirect('market')
		return render(request, self.template_name, {'form': form})


class ContactSupplier(TemplateView):
	template_name = 'contact-supplier/contactsupplier.html'

	def get_context_data(self, **kwargs):
		context = super(ContactSupplier, self).get_context_data(**kwargs)
		context['supplier'] = Supplier.objects.all()[:1]
		return context

def trainingdetail(request):
	return render (request, 'train_detail.html')

home/templates/contact.html
{% load staticfiles %}
<!doctype html>
<html class="no-js" lang="en">
   {% include 'head.html' %}
    <body>
 
 {% include 'navbar.html' %}



        <!-- contact form start here -->
<div class="frm">
    <div class="container">
        <div class="row">
            <div class="col-md-2">
                
            </div>
            <div class="col-md-8">
                <form>
      <div class="form-group">
        <label for="exampleInputEmail1">Name</label>
        <input type="email" class="form-control" id="exampleInputName" placeholder="full-name">
      </div>
      <div class="form-group">
        <label for="exampleInputemail">Email</label>
        <input type="email" class="form-control" id="exampleInputemail" placeholder="email">
      </div>
      <div class="form-group">
        <label for="exampleInputphone">Phone</label>
        <input type="phone" class="form-control" id="exampleInputephone" placeholder="phone no.">
      </div>
      <div class="form-group">
        <label for="exampleInputmessage">message</label>
        <textarea class="form-control" id="exampleInputemessage" row="4" placeholder="message"></textarea>
      </div>
      
      <div class="checkbox">
        <label>
          <input type="checkbox"> Check me out
        </label>
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
      <button type="cancel" class="btn btn-danger">Cancel</button>
    </form>
            </div>
            <div class="col-md-2">
                
            </div>
        </div>
    </div>
</div><br><br><br>
</li></ul></div></nav></div></div></div></div></header>
{% include 'footer.html' %}
</body></html>

home/templates/footer.html

{% load staticfiles %}
           


    <footer class="footer" style="background-color:#29293d; color:white; height:100px;">
      <div class="container-fluid text-center" >
        <h5 style="padding: 28px;">Team TechDivas<br>&copy; Copyright 2017 All Rights Reserved
        </h5>
      </div>
    </footer>




        <script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
        <script>window.jQuery || document.write('<script src="assets/js/vendor/jquery-1.12.0.min.js"><\/script>')</script>
        <!-- Bootstarp js -->
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <!-- Google Map -->
       
        <!-- Custom ScrollBar  -->
        <script src="{% static 'js/enscroll-0.6.2.min.js' %}"></script>
        <!-- LightCase  -->
        <script src="{% static 'js/lightcase.js' %}"></script>
        <!-- Isotop -->
        <script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
        <script src="{% static 'jsjs/custom.isotop.js' %}"></script>
        <!-- Masonry -->
        <script src="{% static 'js/masonry.js' %}"></script>
        <!-- Swipper -->
        <script src="{% static 'js/swiper.min.js' %}"></script>
        <!-- Flex Slider -->
        <script src="{% static 'js/jquery.flexslider.js' %}"></script>
        <!-- NST slider -->
        <script src="{% static 'js/jquery.nstSlider.min.js' %}"></script>
        <!-- Main Js -->
       <!-- <script src="js/functions.js"></script> -->
    </body>
</html>
 

home/templates/head.html
   {% load staticfiles %}
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>GhareluCraft</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="shortcut icon" type="image/x-icon" href="images/favicon.ico" />
        <!-- Bootsrarp Css -->
        <link rel="stylesheet" href="{% static 'css1/bootstrap.min.css' %}">
        <!-- Font Awesome Css -->
        <link rel="stylesheet" href="{% static 'css1/font-awesome.min.css' %}">
        <!-- Reset Css -->
        <link rel="stylesheet" href="{% static 'css1/normalize.css' %}">
        <!-- Flaticon css  -->
        <link rel="stylesheet" href="{% static 'css1/flaticon.css' %}">
        <!-- Swiper Css -->
        <link rel="stylesheet" href="{% static 'css1/swiper.min.css' %}">
        <!-- LightCase css -->
        <link rel="stylesheet" href="{% static 'css1/lightcase.css' %}">
        <!-- flexSlider css -->
        <link rel="stylesheet" href="{% static 'css1/flexslider.css' %}">
        <!-- nstSlider css -->
        <link rel="stylesheet" href="{% static 'css1/jquery.nstSlider.css' %}">
        <!-- Main css -->
        <link rel="stylesheet" href="{% static 'css1/style.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'style1.css' %}">
        <link rel="stylesheet" href="{% static 'css1/responsive.css' %}">
        <script src="{% static 'js/modernizr-2.8.3.min.js' %}"></script>
    </head>

home/templates/index.html
{% load staticfiles %}
<!doctype html>
<html class="no-js" lang="en">
{% include 'head.html'%}
    <body>
 
 {% include 'navbar.html' %}

        <!-- slider -->
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <li data-target="#myCarousel" data-slide-to="3"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="{% static 'images/puppets.jpg' %}" style="height: 600px;" alt="Chania">
    </div>

    <div class="item">
      <img src="{% static 'images/4.jpg' %}" style="height: 600px;" alt="Chania">
    </div>

    <div class="item">
      <img src="{% static 'images/akhijyal.jpg' %}"  style="height: 600px;" alt="Flower">
    </div>

    <div class="item">
      <img src="{% static 'images/woolen.jpg' %}" style="height: 600px;" alt="Flower">
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="" aria-hidden="true"><strong style="font-size: 40px;"><b><</b></strong></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="" aria-hidden="true"><strong style="font-size: 40px;"><b>></b></strong></span>
    <span class="sr-only">Next</span>
  </a>
</div>
        <!-- slider end -->
        <div class="container-fluid space one text-center"">
            <div class="container">
                <div class="row">
                    <div class="col-md-4">
                        <div class="rammmm">
                            <img src="{% static 'images/icon1.png' %}" class="iconHome">
                            <h2>Projects</h2>
                            We have all local small scale handicraft business as well domestic products.
                            <p> 
                        </div>
                        <br>
                        <a href="{% url 'project' %}"><button class="btn btn-danger" style=" background-color: #5cb85c;border-color:#5cb85c; ">View More</button></a>
                    </div>
                    <div class="col-md-4">
                        <div class="rammmm">
                            <img src="{% static 'images/icon1.png' %}" class="iconHome">
                            <h2>About US</h2>
                            <p> We are dedicated to promote local product using local resources by local people</p>
                        </div>
                        <br>
                        <a href="about.html"><button class="btn btn-danger" style=" background-color: #5cb85c; border-color:#5cb85c;  " >View More</button></a>
                        
                    </div>
                    <div class="col-md-4">
                        <div class="rammmm">
                            <img src="{% static 'images/icon1.png' %}" class="iconHome">
                            <h2>Contact Us</h2>
                            <p> To collabrate with us contact us, we provide you proper platform and guidlines</p>
                        </div>
                        <br>
                        <a href="{% url 'contact' %}"><button class="btn btn-danger" style=" background-color: #5cb85c; border-color:#5cb85c; ">View More</button></a>
                        
                    </div>

                </div>
            </div>
        </div>
        <div class="container-fluid height space pebbless text-center"  style="background-color: lightgrey; "><br><br>
    <h1 style="color:#29293d" >"Remember, you will always fail in business if you don't try to open your own business"</h1>
    
</div>

</div>

           







        <script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
        <script>window.jQuery || document.write('<script src="assets/js/vendor/jquery-1.12.0.min.js"><\/script>')</script>
        <!-- Bootstarp js -->
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <!-- Google Map -->
       
        <!-- Custom ScrollBar  -->
        <script src="{% static 'js/enscroll-0.6.2.min.js' %}"></script>
        <!-- LightCase  -->
        <script src="{% static 'js/lightcase.js' %}"></script>
        <!-- Isotop -->
        <script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
        <script src="{% static 'js/custom.isotop.js' %}"></script>
        <!-- Masonry -->
        <script src="{% static 'js/masonry.js' %}"></script>
        <!-- Swipper -->
        <script src="{% static 'js/swiper.min.js' %}"></script>
        <!-- Flex Slider -->
        <script src="{% static 'js/jquery.flexslider.js' %}"></script>
        <!-- NST slider -->
        <script src="{% static 'js/jquery.nstSlider.min.js' %}"></script>
        <!-- Main Js -->
       <!-- <script src="js/functions.js"></script> -->


       {% include 'footer.html' %}
    </body>
</html>
 

home/templates/market.html
{% load staticfiles %}
{% load widget_tweaks %}
<!doctype html>
<html class="no-js" lang="en">
   {% include 'head.html' %}
    <body>
 
 {% include 'navbar.html' %}
 <form method="get">
 <center><div class="row">
        <div class="form-group col-sm-12">
          {{ filter.form.catagories.label_tag }}
          {% render_field filter.form.catagories class="form-control" %}
        </div><br>
        <button type="submit" class="btn btn-primary " style="font-size: 20px;">
        <span class="glyphicon glyphicon-search"></span>Search
      </button>
      </div>
      </form></center><br><br>
 
<div class="container-fluid">
	<div class="container one space">
		<div class="row">
		<h1 class="text-center"><u > Product|Item</u></h1><br><br>
		{% for filter in filter.qs %}
			<div class="col-md-3">
				<div class="market text-center">
				
		 	 		<h4 class="text-center">{{ filter.name}}</h4>
		 	 		<div class="text-center">
		 	 			<img src="{{ filter.image.url}}" class="markThumb" >
		 	 		</div>
		 	 		
		 	 		
		 	 		<button type="button" class="btn btn-info"> 
		 	 		<strong>Price:{{ filter.price }}</strong> </button>
		 	 		<li><STRONG>Quantity:{{ filter.quantity }} </STRONG></li>
		 	 		<li><strong>Description:{{ filter.description }}</strong></li>
		 	 		<br>
		 	 		<button type="button" class="btn btn-danger dang" style="background-color:#5cb85c;border-color: #5cb85c;"> <a href="#"><strong>Contact Us</strong></a> </button>
		 	 		
		 	 	</div><br>
			</div>
			{% endfor %}

	</div>
</div>

<div class="container-fluid space two">
	
	<div class="container one">
	<h1 class="text-center"><u> Sell Your Product Here | Free Promotion </u></h1><br><br>
		<div class="row ">
			<div class="col-md-2">
				
			</div>	
			<div class="col-md-8">
				<form class="form-horizontal well">
  
  <div class="form-group text-center"> 
    <div>
      <a href= "{% url 'supplier-form' %}"<button type="submit" class="btn btn-warning"><strong>Click Here</strong></button></a>
    </div>
  </div>
</form>
			</div>
			<div class="col-md-2">
				
			</div>
		</div>
	</div>
</div>
<div class="container-fluid space">
	
	<div class="container one text-container ">
	<h1 class="text-center"><u> FIND MORE CUSTOMERS; GLOBALLY </u></h1><br>
	<h4>NepBay with its innovative marketing tools helps you reach just over a billion people worldwide.</h4>
	<a href="#">Start Selling</a>
	</div>
</div>

{% include 'footer.html' %}
</body>
</html>

home/templates/navbar.html
     {% load staticfiles %}
       <header class="header">
                
            <div class="mainmenu-area" id="menu-fixed" style=" background-color: #29293d;  height:100px; 
            opacity:0.8;">
                <div class="container">
                    <div class="row">
                    
                        <div class="nav-menu">
                            <nav class="navbar navbar-default">

                                <div class="navbar-header">
                                  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar-one bar-stick"></span>
                                    <span class="icon-bar-two bar-stick"></span>
                                    <span class="icon-bar-three bar-stick"></span>
                                  </button>
                                </div>


                                <div >
                                  <ul class="nav navbar-nav" >
                                  <li>
                                 
                                  <img src="{% static 'images/ghar1.png' %}" style="width:130px; height:100px; padding:10px;" >

                                  </li>

                                    <li >
                                      <a href="{% url 'home' %}" style="color:white; padding-top:40px; padding-left: 100px; ">HOME</a>
                                     
                                    </li>               
                                  
                                    <li class="#">
                                      <a href="{% url 'filter:product-filter' %}" style="color:white; padding-top:40px;"><span>MARKET</span></a>
                                      </li>

                                        <li class="#">
                                      <a href="{% url 'project' %}" style="color:white; padding-top:40px;" >PROJECT</a>
                              
                                    </li>
                                
                                      
                                    <li class="#">
                                      <a href="{% url 'training' %}" style="color:white;padding-top:40px;"><span>TRAINING</span></a>


                                      
                                    </li>

                                     <li><a href="{% url 'forumlist' %}" style="color:white; padding-top:40px;"><span>FORUM</span></a></li>
                                 
                                      <li class="#">
                                      <a href="{% url 'volunteer' %}" style="color:white; padding-top:40px;"><span>VOLUNTEER</span></a>
                             
                                    </li> 
                                
                                    <li><a href="{% url 'login' %}" style="color:white; padding-top:40px;"><span>Login</span></a></li>
                                 

                                  </li>
                                    <li><a href="{% url 'signup' %}" style="color:white; padding-top:40px;"><span>Signup</span></a></li>
                                  </ul>







                                     
                                </div><!-- /.navbar-collapse -->
                            </nav>
                        </div>
                      <!--   <div class="mainmenu-right">
                            <div class="mainmenu-icon">

                                <div class="chart-icon">
                                    
                                      <span class="d"><a href="" style="color:white;
                                      padding-top: 40px;">login</a></span>
                                     
                                    <span class="d"><a href="" style="color:white;
                                    padding-top: 40px;">signup</a></span> -->
                                     
                               <!--      
                                </div>    
                            </div> 
                            
                        </div>  -->                                                 
                        <!--    <div class="search-box-text">
                                <form action="#">
                                    <input type="text" name="search" id="all-search" placeholder="Search Here"/>
                                </form>
                            </div>
                        -->
                    </div>
                </div>
            </div>
        </header>

home/templates/project-knitting1.html
{% load staticfiles %}
<!doctype html>
<html class="no-js" lang="en">
 {% include 'head.html' %}
    <body>
 
      
 {% include 'navbar.html' %}

<!-- <div class="row text-center">
	<div class="col-md-12">
		<h1>Stiching</h1>
		<legend></legend>
	</div>
</div> -->
<div class="container">
	<div class="row text-center">
	<div class="col-md-12">
		
	</div>
</div>
</div>
<div class="container-fluid  space one">
<h1 class="text-center" style="text-transform: uppercase;"><u>Knitting & Stitching | Small Business</u></h1><br>
		<legend></legend> 
	<div class="container ">
		<div class="row text-center">
			<div class="col-md-4"><img src="{% static 'images/knitting3.jpg' %}" class="projectGallery"></div>
			<div class="col-md-4"><img src="{% static 'images/k1.jpg' %}" class="projectGallery"></div>
			<div class="col-md-4"><img src="{% static 'images/k2.jpg' %}" class="projectGallery"></div>
		</div><br>
	
	</div>
</div>
<div class="container-fluid  coll space two">
	<div class="container">
		<div class="row">
			<h2 class="text-center" style="text-transform: uppercase;"><u>Statistical Analysis</u></h2><br>
			<div class="col-md-8">
				<img src="{% static 'images/bargraph.jpg' %}" class="pieone">
			</div>
			<div class="col-md-4">
				<img src="{% static 'images/pie.jpg' %}" class="pie">
			</div>
		</div>
	</div>
</div>

<div class="container-fluid space one">
	<div class="container">
		<div class="col-md-2">
		</div>
		<div class="col-md-8 line">
				<h2 class="text-center" style="text-transform: uppercase;"><u>Specification & Recommendation</u></h2><br>
				<ol>
					<li>Dedication and intrest.</li>
					<li>Atleast 2-3 hours per day.</li>
					<li>CTEVT license exam to start business</li>
					<li>Knitting tools, wool, etc </li>
					<li>Small working area:Home, shop, and in any small place to knit. </li>
					<li>Estimated budget of at least  <button type="button" class="btn btn-success"> <strong>Rs:4,000/</strong> </button></li>
				</ol>
		</div>
		<div class="col-md-2">
		</div>
	</div>
</div>


</div>



<!-- <div class="container-fluid space one">
	<div class="container">
		 <div class="row">
		 	 <h1 class="text-center"style="text-transform: uppercase;"><u>Markets & Demands</u></h1><br>
		 	 {% for supplier in supplier %}
		 	 {% if supplier.publish %}
		 	 <div class="col-md-4 ">
		 	 
		 	 	<div class="market text-center">
		 	 		<h4 class="text-center">{{ supplier.product_name }}</h4>
		 	 		<div class="text-center">
		 	 			<img src="{{ supplier.product_image.url }}" class="markThumb" alt="Woolen Sweater">
		 	 		</div>
		 	 		<li><strong>Demand: </strong>10 pcs/</li>
		 	 		<li><STRONG>Price: </STRONG><button type="button" class="btn btn-info"> <strong>{{ supplier.product_price }}/</strong> </button></li>
		 	 		<strong>Company : {{ supplier.organization }},{{ supplier.location }} </strong>
		 	 		<br>
		 	 		<a href="{% url 'contact-supplier' %}"><button type="button" class="btn btn-danger"> <strong>Contact Supplier</strong></button></a> 
		 	 	</div>
		 	 	
		 	 </div>
		 	 {% endif %}
		 	 {% endfor %}
		 </div>
		 <div class="row">
		 	<br><br>
		 	 
		 	 
		 </div>
	</div>
</div> -->

<div class="container-fluid space two">
	<div class="container">
		<div class="row">
		<h1 class="text-center"style="text-transform: uppercase;"><u>Feedbacks</u></h1><br>
			<div class="col-md-3">
				<img src="{% static 'images/people2.jpg' %}" class="commentPeople">
			</div>
			<div class="col-md-7"><br><br>
				<p class="comment text-center">I am now self dependent and i run my family from this business. I have had trianings and class which have made me earn my living. <br><br><strong>-Saraswati Gautam, Maila Silai Udhyog</strong></p>
			</div>
			<div class="col-md-2"></div>
		</div>
	</div>
	<div class="container">
		<div class="row">
			<div class="col-md-2">
				
			</div>
			<div class="col-md-7"><br><br>
				<p class="comment text-center">I have had trianings and class which have made me earn my living.I have had trianings and class which have made me earn my living.I am now self dependent and i run my family from this business. I have had trianings and class which have made me earn my living. <br><br><strong>-Mina Ale Magar, Saili silai Udhyog</strong></p>
			</div>
			<div class="col-md-3">
				<img src="{% static 'images/people1.jpg' %}" class="commentPeople">
			</div>
		</div>
	</div>
	
</div>

{% include 'footer.html' %}
</body>
</html>

home/templates/project.html
{% load staticfiles %}
<!doctype html>
<html class="no-js" lang="en">
   {% include 'head.html' %}
    <body>
 
       
 {% include 'navbar.html' %}



   


<div class="container-fluid space one">
	 <div class="container">
	 	<h1 class="text-center"><u> Gharelu Crafts Projects </u></h1><br>
		
		 	<div class="row">
				<div class="col-md-4">
					<div class="phome text-center">
						<h2>Woollen craft</h2>
						<img src="{% static 'images/project.jpg' %}" class="img-rounded proj" ><br>
						<a href="{% url 'knitting' %}"><button class="btn 	btn-success"><strong><b>View Details</b></strong></button></a>
					</div>
				</div>
				<div class="col-md-4">
					<div class="phome text-center">
						<h2>Dhaka craft </h2>
						<img src="{% static 'images/dhakap.jpg' %}" class="img-rounded proj" ><br>
						<a href="project-knitting.html"><button class="btn 	btn-success"><strong><b>View Details</b></strong></button></a>
					</div>
				</div>
				<div class="phome text-center">
						<h2>Pashmina craft</h2>
						<img src="{% static 'images/pashminap.png' %}" class="img-rounded proj" ><br>
						<a href="project-knitting.html"><button class="btn 	btn-success"><strong><b>View Details</b></strong></button></a>
					</div>
				
				</div><br><br>

				<div class="row">
		
				<div class="col-md-4">
				<div class="phome text-center">
						<h2>Ceramics craft</h2>
						<img src="{% static 'images/candel.jpg' %}" class="img-rounded proj" ><br>
						<a href="project-knitting.html"><button class="btn 	btn-success"><strong><b>View Details</b></strong></button></a>
					</div>
					
				</div>
				<div class="col-md-4">
					<div class="phome text-center">
						<h2>Silk </h2>
						<img src="{% static 'images/silkp.jpeg' %}" class="img-rounded proj" ><br>
						<a href="project-knitting.html"><button class="btn 	btn-success"><strong><b>View Details</b></strong></button></a>
					</div>
				</div>
				<div class="col-md-4">
					<div class="phome text-center">
						<h2>Cotton</h2>
						<img src="{% static 'images/cottonP.jpg' %}" class="img-rounded proj" ><br>
						<a href="project-knitting.html"><button class="btn 	btn-success"><strong><b>View Details</b></strong></button></a>
					</div><br>
			
					
				</div>



       <div class="row">
				<div class="col-md-4">
					<div class="phome text-center">
						<h2>Metal Craft</h2>
						<img src="{% static 'images/pot.jpg' %}" class="img-rounded proj" ><br>
						<a href="project-knitting.html"><button class="btn 	btn-success"><strong><b>View Details</b></strong></button></a>
					</div>
				</div>
				<div class="col-md-4">
					<div class="phome text-center">
						<h2>Wood Craft</h2>
						<img src="{% static 'images/wood.jpg' %}" class="img-rounded proj" ><br>
						<a href="project-knitting.html"><button class="btn 	btn-success"><strong><b>View Details</b></strong></button></a>
					</div>
				</div>
				<div class="col-md-4">
					<div class="phome text-center">
						<h2>Bamboo Craft</h2>
						<img src="{% static 'images/bam.jpg' %}" class="img-rounded proj" ><br>
						<a href="project-knitting.html"><button class="btn 	btn-success"><strong><b>View Details</b></strong></button></a>
					</div>
				</div>
			</div><br><br>

			
			<center><button type="button"  class="btn btn-danger" style="background-color:#29293d ; border-color: #29293d ; color:white; padding:16px;">More project</button></center><br><br>
	 </div>
</div>
<div class="container-fluid height space pebbless text-center"><br><br>
	<h1 ><img src="{% static 'images/quote.png' %}" class="quote">Remember, you will always fail in business if you don't try to open your own business"</h1>
	<h2>-Amit Kalantri</h2><br>
</div>

</li>
</ul>
</div>
</nav>
</div>
</div>
</div>
</div>
</header>
</body>
{% include 'footer.html' %}
</html>

home/templates/supplier_form.html
{% load staticfiles %}
<!doctype html>
<html class="no-js" lang="en">
   {% include 'head.html' %}
    <body>
 
 {% include 'navbar.html' %}


<br><br>
<div class="container-fluid space one ">
	<form method='post' enctype = 'multipart/form-data'> {% csrf_token %}
{{ form.as_p }}
<input type="submit" name="Send" value="Submit"/>
</form>
</div>